// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CicekSepeti.Feature
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("CicekSepeti")]
    public partial class CicekSepetiFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "CicekSepeti.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "CicekSepeti", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line 7
testRunner.And("\'Chrome\' driver ile browser acilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LolafloraSignInPageSuccessfulLoginWithValidEmailAndPassword")]
        public virtual void LolafloraSignInPageSuccessfulLoginWithValidEmailAndPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LolafloraSignInPageSuccessfulLoginWithValidEmailAndPassword", ((string[])(null)));
#line 8
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 9
 testRunner.And("\'https://www.lolaflora.com/login\' sayfasina gidilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 10
 testRunner.And("Email alanina \'validemail@gmail.com\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 11
 testRunner.And("Password alanina \'ValidPassword@123\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 12
 testRunner.And("Sign In butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 13
 testRunner.And("Basarili giris yapildigi gorulur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LolafloraSignInPageSuccessfulLoginViaFacebook")]
        public virtual void LolafloraSignInPageSuccessfulLoginViaFacebook()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LolafloraSignInPageSuccessfulLoginViaFacebook", ((string[])(null)));
#line 15
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 16
 testRunner.And("\'https://www.lolaflora.com/login\' sayfasina gidilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 17
 testRunner.And("Sign in with Facebook butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 18
 testRunner.And("\'1\' nolu pencereye gecilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 19
 testRunner.And("Eposta alanina \'validemail@gmail.com\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 20
 testRunner.And("Sifre alanina \'ValidPassword@123\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 21
 testRunner.And("Giris yap butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 22
 testRunner.And("\'0\' nolu pencereye gecilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 23
 testRunner.And("Basarili giris yapildigi gorulur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LolafloraSignInPageUnsuccessfulLoginWithValidEmailAndWrongPassword")]
        public virtual void LolafloraSignInPageUnsuccessfulLoginWithValidEmailAndWrongPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LolafloraSignInPageUnsuccessfulLoginWithValidEmailAndWrongPassword", ((string[])(null)));
#line 25
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 26
 testRunner.And("\'https://www.lolaflora.com/login\' sayfasina gidilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 27
 testRunner.And("Email alanina \'validmail@gmail.com\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 28
 testRunner.And("Password alanina \'wrongpassword\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 29
 testRunner.And("Sign In butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 30
 testRunner.And("Hatali giris ile ilgili popup mesaji gorulur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LolafloraSignInPageUnsuccessfulLoginWithWrongEmailAndValidPassword")]
        public virtual void LolafloraSignInPageUnsuccessfulLoginWithWrongEmailAndValidPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LolafloraSignInPageUnsuccessfulLoginWithWrongEmailAndValidPassword", ((string[])(null)));
#line 32
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 33
 testRunner.And("\'https://www.lolaflora.com/login\' sayfasina gidilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 34
 testRunner.And("Email alanina \'wrong@gmail.com\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 35
 testRunner.And("Password alanina \'ValidPassword@123\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 36
 testRunner.And("Sign In butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 37
 testRunner.And("Hatali giris ile ilgili popup mesaji gorulur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LolafloraSignInPageUnsuccessfulLoginWithEmptyMailAndEmptyPassword")]
        public virtual void LolafloraSignInPageUnsuccessfulLoginWithEmptyMailAndEmptyPassword()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LolafloraSignInPageUnsuccessfulLoginWithEmptyMailAndEmptyPassword", ((string[])(null)));
#line 39
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 40
 testRunner.And("\'https://www.lolaflora.com/login\' sayfasina gidilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 41
 testRunner.And("Sign In butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 42
 testRunner.And("Email alani altinda \'Required field.\' hatasi gorulur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 43
 testRunner.And("Password alani altinda \'Required field.\' hatasi gorulur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("LolafloraSignInPageForgotPasswordSuccessfulSending")]
        public virtual void LolafloraSignInPageForgotPasswordSuccessfulSending()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("LolafloraSignInPageForgotPasswordSuccessfulSending", ((string[])(null)));
#line 45
this.ScenarioSetup(scenarioInfo);
#line 6
this.FeatureBackground();
#line 46
 testRunner.And("\'https://www.lolaflora.com/login\' sayfasina gidilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 47
 testRunner.And("Forgot Password butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 48
 testRunner.And("Mail alanina \'ciceksepeti@gmail.com\' yazilir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 49
 testRunner.And("Send butonuna tiklanir", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line 50
 testRunner.And("Email gonderiminin basarili oldugu gorulur", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "* ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

